swagger: "2.0"
info:
  version: "0.2.0"
  title: Traits App API
# during dev, should point to your local machine
host: traits-app-api.herokuapp.com #localhost:3000 #
# basePath prefixes all resource paths 
basePath: /api
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /trait:
    # our controller name
    #x-swagger-router-controller: description
    post:
      #operationId: save_description
      tags: [Trait]
      description: add a new trait
      # movie info to be stored
      parameters:
        - name: type
          description: trait description
          in: body
          required: true
          schema:
            $ref: "#/definitions/Trait"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GeneralResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /trait/{type}:
    # our controller name
    #x-swagger-router-controller: people
    get:
      #perationId: get_people_by_type
      tags: [Trait]
      description: get trait by type
      # define the type of response for Success "200" and Error
      parameters:
        - name: type
          type: string
          in: path
          required: true
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GetTraitsListResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /userTraits/{username}:
    put:
      #operationId: update_user_traits
      tags: [User Traits]
      description: update a user trait
      # define the parameters
      parameters:
        - name: username
          description: Username
          type: string
          in: path
          required: true
        - name: usertrait
          description: User traits properties
          in: body
          required: true
          schema:
            $ref: "#/definitions/UserTraits"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GeneralResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /story:
    # our controller name
    #x-swagger-router-controller: description
    post:
      #operationId: save_description
      tags: [Story]
      description: add a new story
      # movie info to be stored
      parameters:
        - name: type
          description: story properties
          in: body
          required: true
          schema:
            $ref: "#/definitions/Story"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GeneralResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /stories/{type}:
    # our controller name
    #x-swagger-router-controller: description
    get:
      #operationId: get_descriptions_by_type
      tags: [Story]
      description: get stories by type
      # define the type of response for Success "200" and Error
      parameters:
        - name: type
          type: string
          in: path
          required: true
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GetDescriptionListResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /people:
    # our controller name
    #x-swagger-router-controller: people
    get:
      #operationId: get_all_people
      tags: [People]
      description: get people list
      # define the type of response for Success "200" and Error
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GetPeopleListResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    post:
      #operationId: save_people
      tags: [People]
      description: add a new person to the list
      # movie info to be stored
      parameters:
        - name: type
          description: People properties
          in: body
          required: true
          schema:
            $ref: "#/definitions/People"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GeneralResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /people/{type}:
    # our controller name
    #x-swagger-router-controller: people
    get:
      #perationId: get_people_by_type
      tags: [People]
      description: get people by type
      # define the type of response for Success "200" and Error
      parameters:
        - name: type
          type: string
          in: path
          required: true
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GetPeopleListResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /personality:
    # our controller name
    #x-swagger-router-controller: personality
    get:
      #operationId: get_all_personalities
      tags: [Personality]
      description: get personality list
      # define the type of response for Success "200" and Error
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GetPersonalitysListResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    post:
      #operationId: save_personality
      tags: [Personality]
      description: add a new personality to the list
      # movie info to be stored
      parameters:
        - name: type
          description: Personality properties
          in: body
          required: true
          schema:
            $ref: "#/definitions/Personality"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GeneralResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /personality/{type}:
    # our controller name
    #x-swagger-router-controller: personality
    get:
      #operationId: get_personality
      tags: [Personality]
      description: get a personality
      # define the type of response for Success "200" and Error
      parameters:
        - name: type
          type: string
          in: path
          required: true
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GetPersonalityResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /userTypePart/{username}:
    put:
      #operationId: update_user_type_part
      tags: [User Type Part]
      description: update a user type part
      # define the parameters
      parameters:
        - name: username
          description: username
          type: string
          in: path
          required: true
        - name: usertypepart
          description: User type part properties
          in: body
          required: true
          schema:
            $ref: "#/definitions/UserTypePart"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GeneralResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /user:
    # our controller name
    #x-swagger-router-controller: user
    post:
      #operationId: save_user
      tags: [User]
      description: add a new user to the list
      # movie info to be stored
      parameters:
        - name: email
          description: User properties
          in: body
          required: true
          schema:
            $ref: "#/definitions/User"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GetUserResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /usersignin:
    # our controller name
    #x-swagger-router-controller: user
    post:
      #operationId: user_signin
      tags: [User]
      description: add a new user to the list
      # movie info to be stored
      parameters:
        - name: email
          description: User properties
          in: body
          required: true
          schema:
            $ref: "#/definitions/UserSignin"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GetUserResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  GetDescriptionListResponse:
    required:
      - descriptions
    properties:
      # The array of movies
      descriptions:
        type: array
        items: 
          type: object
          properties:
            title:
              type: string
            description:
              type: string
            tags:
              type: string
            source:
              type: string
            timestamp:
              type: string
            personalitytype:
              type: string
  GetTraitsListResponse:
    required:
      - traits_list
    properties:
      # The array of traits
      traits_list:
        type: array
        items: 
          type: object
          properties:
            id:
              type: string
            type:
              type: string
            trait:
              type: string
            weight:
              type: number
    
  GetPeopleListResponse:
    required:
      - people_list
    properties:
      # The array of peeps
      people_list:
        type: array
        items: 
          type: object
          properties:
            id:
              type: string
            name:
              type: string
            lastname:
              type: string
            occupation:
              type: string
            isreal:
              type: string
            from:
              type: string
            personalitytype:
              type: string
  GetPersonalitysListResponse:
    required:
      - personalities
    properties:
      # The array of users
      personalities:
        type: array
        items: 
          type: object
          properties:
            id:
              type: string
            type:
              type: string
            totalfrequency:
              type: string
            malefrequency:
              type: string
            femalefrequency:
              type: string
            description:
              type: string
            typefull:
              type: string
            color:
              type: string
  GetUserResponse:
    required:
      - email
    properties:
      id:
        type: string
      name:
        type: string
      lastname:
        type: string
      email: 
        type: string
      username:
        type: string
      passwordHash:
        type: string
      salt:
        type: string
      usertypeparts:
        type: array
        items:
          $ref: "#/definitions/TypePart"
      usertraits:
        type: array
        items:
          $ref: "#/definitions/UserTraits"
          
  GetPersonalityResponse:
    required:
      - type
    properties:
      id:
        type: string
      type:
        type: string
      totalfrequency:
        type: string
      malefrequency:
        type: string
      femalefrequency:
        type: string
      description:
        type: string
      typefull:
        type: string
      color:
        type: string
  UserTypePart:
    type: object
    properties:
      type_percentage:
        type: array
        items: 
         $ref: "#/definitions/TypePart"
  TypePart:
    type: object
    properties:
      personalitytype:
        type: string
        description: Personality type
      percentage:
        type: string
        description: Personality percentage
      lastupdate:
        type: string
        format: date-time
        description: Last update. E.g. '2016-06-17T15:28:34Z' (RFC 3339, ISO 8601)
        
  UserTraits:
    type: object
    properties:
      personalitytype:
        type: string
        description: personality type for user selected traits
      traits:
        type: array
        items: {
          type: string
        }
  Trait:
    type: object
    properties:
      type:
        type: string
        description: Personality type
      trait:
        type: string
        description: Personality trait
      weight:
        type: number
        description: weight determined by how often the trait is used for the personality type
  
  User:
    type: object
    properties:
      email:
        type: string
        description: task object name
      password:
        type: string
        description: task object password
      name:
        type: string
        description: user name
      lastname:
        type: string
        description: user lastname
      timestamp:
        type: string
        format: date-time
        description: The date the user registered (E.g. '2016-06-17T15:28:34Z' (RFC 3339, ISO 8601))
      usertraits:
        type: array
        items:
          $ref: "#/definitions/UserTraits"
          
    required:
      - email
      - password
  UserSignin:
    type: object
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
        
  Personality:
    type: object
    properties:
      type:
        type: string
        description: task object name
      totalfrequency:
        type: string
        description: task description
      malefrequency:
        type: string
        description: task description
      femalefrequency:
        type: string
        description: task description
      description:
        type: string
        description: task description
      typefull:
        type: string
        description: task description
      color:
        type: string
        description: task description
    required:
      - type
      
  People:
    type: object
    properties:
      name:
        type: string
      lastname:
        type: string
      occupation:
        type: string
      isreal:
        type: string
      info:
        type: string
      personalitytype:
        type: string
      tags:
        type: array
        items: {
          type: string
        }
    required:
      - name
      
  Story:
    type: object
    properties:
      title:
        type: string
      description:
        type: string
      source:
        type: string
      timestamp:
        type: string
      personalitytype:
        type: string
      tags:
        type: array
        items: {
          type: string
        }
    required:
      - title
      
  GeneralResponse:
    type: object
    properties:
      success:
        type: number
        description: returns 1 if successful
      description:
        type: string
        description: a short comment 
    required:
      - success
      - description
      
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
